# =====================================================
# DISCOVERY SERVER (Eureka) — Port 8761
# =====================================================
# Ce service DOIT démarrer EN PREMIER.
# URL dashboard : http://localhost:8761
# =====================================================

spring.application.name=discovery-server
server.port=8761

# Configuration Eureka Server
# fetchRegistry=false : ce serveur ne cherche pas d'autres serveurs
# registerWithEureka=false : ce serveur ne s'enregistre pas lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL du serveur (utilisée dans les logs)
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Dashboard Eureka
eureka.server.enable-self-preservation=false

# Désactive la sécurité pour le dashboard en développement
spring.security.user.name=admin
spring.security.user.password=admin123

logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
